name: Build & Deploy to GitHub Pages

# 0. Permissions requises pour que GITHUB_TOKEN puisse git push et déployer
permissions:
  contents: write   # permet de push le commit du build
  pages: write      # permet de publier sur GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code et préserver le token pour la suite
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. Installer Node.js ≥ 20.19 et activer le cache npm
      - name: Setup Node.js ≥ 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      # 3. Installer les dépendances & builder dans frontend/
      - name: Install & Build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # 4. Publier le résultat sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
